[profile.default]
solc = '0.8.20'
out = 'out'
fuzz_runs = 1000
optimizer_runs = 100
optimizer_details.deduplicate = true
optimizer_details.cse = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
remappings = [
  "@openzeppelin-pike/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
  "@oz-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@wormhole/=src/contracts/gateway/channels/wormhole/",
  "@pyth-network/=lib/@pyth-network/",
  "@hub/=src/contracts/hub/",
  "@spoke/=src/contracts/spoke/",
  "@gateway/=src/contracts/gateway/",
  "@utils/=src/contracts/utils/",
  "@types/=src/contracts/types/",
  "ds-test/=lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "isolmate/=lib/isolmate/src/",
  "@prb/math/=lib/prb-math/src/",
  "prb-test/=lib/prb-test/src/",
  "prb/test/=lib/prb-test/src/",
  "@gelatonetwork/=lib/@gelatonetwork/contracts/"
]
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.optimized]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000

[profile.test]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000
src = 'src/test'

[rpc_endpoints]
base = "${BASE_MAINNET_RPC}"
eth = "${ETH_MAINNET_RPC}"
arb = "${ARB_MAINNET_RPC}"
op = "${OP_MAINNET_RPC}"
base-sepolia = "${BASE_SEPOLIA_RPC}"
sepolia = "${ETH_SEPOLIA_RPC}"
arb-sepolia = "${ARB_SEPOLIA_RPC}"
op-sepolia = "${OP_SEPOLIA_RPC}"
bsc-goerli = "${BSC_GOERLI_RPC}"
avax-goerli = "${AVAX_GOERLI_RPC}"
poly-goerli = "${POLY_GOERLI_RPC}"
moon-goerli = "${MOON_GOERLI_RPC}"

[fmt]
line_length = 90
tab_width = 4
bracket_spacing = false
int_types = 'long'
quote_style = 'double'
number_underscore = 'thousands'
multiline_func_header = 'all'
